import Navbar from "@/components/Header/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
